sudo: required
dist: trusty
language: node_js
before_install:
  - cp config.sample.js config.js
  - sed -i 's/pass:.*/pass:"travis",/' config.js
  - sed -i 's/root/travis/' config.js
  - docker run -d --net=host sparkida/pure-ftpd
  - sleep 1
node_js:
    - '7.6.0'
git:
    depth: 3
